# Generated by Django 5.2.5 on 2025-08-19 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aeronave",
            name="custo_hora_voo",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Custo da hora de voo em R$.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="ordemservico",
            name="custo_total_estimado",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Custo total estimado da operação em R$.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="produto",
            name="custo_por_litro",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Custo do produto em R$ por litro.",
                max_digits=10,
            ),
        ),
    ]
