# Generated by Django 5.2.5 on 2025-08-19 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_create_groups"),
    ]

    operations = [
        migrations.CreateModel(
            name="EstoqueProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade_litros",
                    models.FloatField(
                        default=0.0, help_text="Quantidade disponível em litros."
                    ),
                ),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
                (
                    "fazenda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="core.fazenda",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estoques",
                        to="core.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque de Produto",
                "verbose_name_plural": "Estoques de Produtos",
                "unique_together": {("produto", "fazenda")},
            },
        ),
    ]
